table inet nat {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
        iifname "enp1s0" udp dport 57575 daddr 192.168.5.254 tee to 127.0.0.1:57575
        iifname "enp1s0" udp dport 57575 daddr 192.168.5.254 dnat to mcogs.coslabs.com:57575
    }

    chain postrouting {
        type nat hook postrouting priority scrnat; policy accept;
        oifname != "enp1s0" masquerade
    }
}

table inet filter {
    chain forward {
        type filter hook forward priority filter; policy accept;
        iifname "enp1s0" oifname != "enp1s0" udp dport 57575 daddr mcogs.coslabs.com accept
    }
}